### ISSUE TITLE
Asks for wrong permission on the custom screen

### ISSUE THREAD

**Issue by younisshah** [ayz4sci/permissionHelper#1]
I'm running Android N on Google Nexus 5X. I need to scan a QR code for which I need permission to access the CAMERA. Using your library, everything is working fine, except that instead of displaying the string "Access your camera", the custom screen displays "Access your calendar".

**Comment by ayz4sci** [comment]
What permission did you pass to it?

**Comment by younisshah** [comment]
These: `<uses-permission android:name="android.permission.CAMERA" />`

I got it running with a hack - like this:

`((TextView)permissionHelper.getPermissionDialog()                                         .findViewById(com.ayz4sci.androidfactory.permissionhelper.R.id.permission_description))
.setText("Access your CAMERA");`

**Comment by ayz4sci** [comment]
I found the error and fixed it. 
I published version 1.1.0
compile 'com.ayz4sci.androidfactory:permissionhelper:1.1.0'
